(function () {
window.GeoMaster = window.GeoMaster || {};

const BASE_SOURCE_ID = 'country-flag-icons';
const LOCAL_FLAG_STATUS = 'Local/unofficial flag';
const LOCAL_FLAG_DESCRIPTION = 'Local/unofficial flag; official flag is France\u2019s tricolour.';

// These keys intentionally match the canonical map names in countries.js rather
// than attempting to normalize or rename them at runtime.
const flagCodesByCountry = Object.freeze({
  'Lebanon': 'LB',
  'Mauritius': 'MU',
  'Nauru': 'NR',
  'Dominica': 'DM',
  'Bulgaria': 'BG',
  'Azerbaijan': 'AZ',
  'Guadeloupe': 'GP',
  'United States Virgin Islands': 'VI',
  'Paraguay': 'PY',
  'Cuba': 'CU',
  'Argentina': 'AR',
  'Sweden': 'SE',
  'Bermuda': 'BM',
  'Croatia': 'HR',
  'Macedonia': 'MK',
  'Mauritania': 'MR',
  'France': 'FR',
  'Burkina Faso': 'BF',
  'Turks and Caicos Islands': 'TC',
  'Jamaica': 'JM',
  'Chile': 'CL',
  'Guinea-Bissau': 'GW',
  'Austria': 'AT',
  'Western Sahara': 'EH',
  'Togo': 'TG',
  'Saudi Arabia': 'SA',
  'Uruguay': 'UY',
  'Portugal': 'PT',
  'Tajikistan': 'TJ',
  'Cameroon': 'CM',
  'Sint Maarten': 'SX',
  'Qatar': 'QA',
  'Mexico': 'MX',
  'Marshall Islands': 'MH',
  'Trinidad and Tobago': 'TT',
  'Botswana': 'BW',
  'Fiji': 'FJ',
  'Greece': 'GR',
  'Palestine': 'PS',
  'Ireland': 'IE',
  'Cyprus': 'CY',
  'South Africa': 'ZA',
  'Reunion': 'RE',
  'Haiti': 'HT',
  'Benin': 'BJ',
  'Cayman Islands': 'KY',
  'Greenland': 'GL',
  'Montenegro': 'ME',
  'Pakistan': 'PK',
  'Guyana': 'GY',
  'Panama': 'PA',
  'Saint-Barthelemy': 'BL',
  'South Sudan': 'SS',
  'Kyrgyzstan': 'KG',
  'Bosnia and Herzegovina': 'BA',
  'Burundi': 'BI',
  'Estonia': 'EE',
  'Vanuatu': 'VU',
  'Switzerland': 'CH',
  'Costa Rica': 'CR',
  'Chad': 'TD',
  'Suriname': 'SR',
  'Saba (Netherlands)': 'BQ-SA',
  'Ecuador': 'EC',
  'Palau': 'PW',
  'Afghanistan': 'AF',
  'Norway': 'NO',
  'Romania': 'RO',
  'Canada': 'CA',
  'Rwanda': 'RW',
  'Belize': 'BZ',
  'Bangladesh': 'BD',
  'Zambia': 'ZM',
  'United States': 'US',
  'Malta': 'MT',
  'St. Eustatius (Netherlands)': 'BQ-SE',
  'Syria': 'SY',
  'Saint Kitts and Nevis': 'KN',
  'Bahrain': 'BH',
  'Nigeria': 'NG',
  'Sao Tome and Principe': 'ST',
  'Moldova': 'MD',
  'Gabon': 'GA',
  'Falkland Islands': 'FK',
  'India': 'IN',
  'Saint Lucia': 'LC',
  'China': 'CN',
  'Federated States of Micronesia': 'FM',
  'American Samoa': 'AS',
  'Slovenia': 'SI',
  'United Arab Emirates': 'AE',
  'Bolivia': 'BO',
  'Senegal': 'SN',
  'Japan': 'JP',
  'Namibia': 'NA',
  'Sudan': 'SD',
  'Iran': 'IR',
  'Serbia': 'RS',
  'Guinea': 'GN',
  'Belarus': 'BY',
  'Turkmenistan': 'TM',
  'South Korea': 'KR',
  'Papua New Guinea': 'PG',
  'Cambodia': 'KH',
  'Nicaragua': 'NI',
  'Venezuela': 'VE',
  'Bahamas': 'BS',
  'Uzbekistan': 'UZ',
  'Northern Mariana Islands': 'MP',
  'Grenada': 'GD',
  'Curacao': 'CW',
  'Lao People\'s Democratic Republic': 'LA',
  'Antigua and Barbuda': 'AG',
  'Tanzania': 'TZ',
  'Eritrea': 'ER',
  'Ethiopia': 'ET',
  'Seychelles': 'SC',
  'Madagascar': 'MG',
  'British Virgin Islands': 'VG',
  'Yemen': 'YE',
  'Kazakhstan': 'KZ',
  'French Polynesia': 'PF',
  'Republic of Congo': 'CG',
  'Cote d\'Ivoire': 'CI',
  'Morocco': 'MA',
  'Timor-Leste': 'TL',
  'Guam': 'GU',
  'Indonesia': 'ID',
  'Albania': 'AL',
  'Israel': 'IL',
  'Spain': 'ES',
  'Democratic Republic of the Congo': 'CD',
  'Philippines': 'PH',
  'Netherlands': 'NL',
  'Belgium': 'BE',
  'Ghana': 'GH',
  'Vietnam': 'VN',
  'French Guiana': 'GF',
  'Brazil': 'BR',
  'Tuvalu': 'TV',
  'Jordan': 'JO',
  'Iceland': 'IS',
  'Australia': 'AU',
  'Germany': 'DE',
  'Dominican Republic': 'DO',
  'Libya': 'LY',
  'Mozambique': 'MZ',
  'Niger': 'NE',
  'Zimbabwe': 'ZW',
  'Sri Lanka': 'LK',
  'Georgia': 'GE',
  'Oman': 'OM',
  'Ukraine': 'UA',
  'Barbados': 'BB',
  'Finland': 'FI',
  'Malawi': 'MW',
  'Guatemala': 'GT',
  'Czech Republic': 'CZ',
  'Poland': 'PL',
  'Saint Vincent and the Grenadines': 'VC',
  'Aruba': 'AW',
  'Kosovo': 'XK',
  'Myanmar': 'MM',
  'Egypt': 'EG',
  'Faeroe Islands': 'FO',
  'Slovakia': 'SK',
  'Maldives': 'MV',
  'Armenia': 'AM',
  'Turkey': 'TR',
  'Denmark': 'DK',
  'Somalia': 'SO',
  'Algeria': 'DZ',
  'Solomon Islands': 'SB',
  'Mali': 'ML',
  'Tunisia': 'TN',
  'El Salvador': 'SV',
  'Italy': 'IT',
  'Comoros': 'KM',
  'Cape Verde': 'CV',
  'Saint-Martin': 'MF',
  'Brunei': 'BN',
  'Equatorial Guinea': 'GQ',
  'New Zealand': 'NZ',
  'Samoa': 'WS',
  'Mayotte': 'YT',
  'Iraq': 'IQ',
  'Malaysia': 'MY',
  'Honduras': 'HN',
  'Peru': 'PE',
  'Thailand': 'TH',
  'Djibouti': 'DJ',
  'Luxembourg': 'LU',
  'Montserrat': 'MS',
  'Lesotho': 'LS',
  'Uganda': 'UG',
  'Lithuania': 'LT',
  'New Caledonia': 'NC',
  'Taiwan': 'TW',
  'Hungary': 'HU',
  'Latvia': 'LV',
  'North Korea': 'KP',
  'Kuwait': 'KW',
  'Nepal': 'NP',
  'Anguilla': 'AI',
  'Mongolia': 'MN',
  'Colombia': 'CO',
  'Puerto Rico': 'PR',
  'Canary Islands (Spain)': 'IC',
  'Tonga': 'TO',
  'Swaziland': 'SZ',
  'Angola': 'AO',
  'Russia': 'RU',
  'Sierra Leone': 'SL',
  'Martinique': 'MQ',
  'United Kingdom': 'GB',
  'Kenya': 'KE',
  'Liberia': 'LR',
  'The Gambia': 'GM',
  'Central African Republic': 'CF',
  'Bhutan': 'BT',
});

const overridesByCountry = Object.freeze({
  'Guadeloupe': Object.freeze({
    sourceId: 'wikimedia-guadeloupe-local',
    statusLabel: LOCAL_FLAG_STATUS,
    statusDescription: LOCAL_FLAG_DESCRIPTION,
  }),
  'Reunion': Object.freeze({
    sourceId: 'wikimedia-reunion-var',
    statusLabel: LOCAL_FLAG_STATUS,
    statusDescription: LOCAL_FLAG_DESCRIPTION,
  }),
});

const sources = Object.freeze({
  'country-flag-icons': Object.freeze({
    name: 'country-flag-icons',
    version: '1.6.20',
    commit: '3b8ea50f08ab9d5e79c90325ff76606a4258a719',
    integrity: 'sha512-py8JiEKzjhYw6HPJ0L7SxLgCYim36UPRTZX43/kqGueUCZLSvnrqAiwW8HtQibur7mdkFQUkjOgdK+o/9FBtaw==',
    license: 'MIT',
    repository: 'https://gitlab.com/catamphetamine/country-flag-icons',
  }),
  'wikimedia-guadeloupe-local': Object.freeze({
    name: 'Unofficial flag of Guadeloupe (local)',
    author: 'Pierre Gay; SVG revisions by Wikimedia Commons contributors',
    source: 'https://commons.wikimedia.org/wiki/File:Unofficial_flag_of_Guadeloupe_(local).svg',
    sourceSha1: 'bb2645e2ba2a59656157f8f0f53d213e66b47568',
    license: 'Public domain (ineligible for copyright)',
  }),
  'wikimedia-reunion-var': Object.freeze({
    name: 'Proposed flag of Reunion (VAR / Lo Mahaveli)',
    author: 'Ch1902; SVG revision by SiBr4',
    source: 'https://commons.wikimedia.org/wiki/File:Proposed_flag_of_R%C3%A9union_(VAR).svg',
    sourceSha1: '24f4e4bfe47d7af1115fdab410093875ed072536',
    license: 'Public domain dedication',
  }),
});

const flagsByCountry = Object.freeze(Object.fromEntries(
  Object.entries(flagCodesByCountry).map(([country, code]) => {
    const override = overridesByCountry[country];
    return [country, Object.freeze({
      country,
      code,
      src: `assets/flags/${code.toLowerCase()}.svg`,
      visualId: `flag:${code.toLowerCase()}`,
      statusLabel: override ? override.statusLabel : null,
      statusDescription: override ? override.statusDescription : null,
      sourceId: override ? override.sourceId : BASE_SOURCE_ID,
    })];
  }),
));

function getFlag(country) {
  return flagsByCountry[country] || null;
}

window.GeoMaster.countryFlags = Object.freeze({
  flagsByCountry,
  getFlag,
  sources,
});

})();
